/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_rules"];
        put?: never;
        post: operations["create_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_rule"];
        put: operations["update_rule"];
        post?: never;
        delete: operations["delete_rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_keys"];
        put?: never;
        post: operations["create_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation: atomically claims the token, creates the user, and issues session tokens. */
        post: operations["accept_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invite/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a pending invite by token to populate the accept-invite form. */
        get: operations["get_invite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current user info (used by frontend to check if session is active). */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all orgs the current user belongs to (for org switcher). */
        get: operations["list_user_orgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["switch_org"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_brokers"];
        put?: never;
        post: operations["create_broker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_broker"];
        put?: never;
        post?: never;
        delete: operations["delete_broker"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers/{id}/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_broker_queues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_broker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_broker_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brokers/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop_broker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/failure-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["failure_groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/queue-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue_names"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/queue-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/task-name-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task_name_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/task-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task_names"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["throughput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_queues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_notifications"];
        put: operations["update_notifications"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_notification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_retention"];
        put: operations["update_retention"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent dead-letter entries for the authenticated tenant. */
        get: operations["dead_letters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full system health: component statuses, pipeline metrics, storage info. */
        get: operations["system_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pipeline ingestion metrics (from Redis counters). */
        get: operations["pipeline_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_task_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retry_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry-chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_retry_chain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revoke_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_task_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["invite_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_workers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["worker_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["worker_task_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{worker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_worker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{worker_id}/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shutdown_worker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{root_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_workflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteRequest: {
            display_name?: string | null;
            password: string;
            token: string;
        };
        /** @description Alert notification channel configuration. */
        AlertChannel: {
            /** @enum {string} */
            type: "slack";
            webhook_url: string;
        } | {
            to: string[];
            /** @enum {string} */
            type: "email";
        } | {
            headers?: {
                [key: string]: string;
            } | null;
            /** @enum {string} */
            type: "webhook";
            url: string;
        } | {
            routing_key: string;
            /** @enum {string} */
            type: "pagerduty";
        };
        AlertCondition: {
            task_name?: string;
            /** Format: double */
            threshold: number;
            /** @enum {string} */
            type: "task_failure_rate";
            /** Format: int64 */
            window_minutes: number;
        } | {
            queue: string;
            /** Format: int64 */
            threshold: number;
            /** @enum {string} */
            type: "queue_depth";
        } | {
            /** Format: int64 */
            grace_period_seconds: number;
            /** @enum {string} */
            type: "worker_offline";
        } | {
            /** Format: double */
            percentile: number;
            task_name?: string;
            /** Format: double */
            threshold_seconds: number;
            /** @enum {string} */
            type: "task_duration";
        } | {
            schedule_name: string;
            /** @enum {string} */
            type: "beat_missed";
        } | {
            task_name?: string;
            /** @enum {string} */
            type: "task_failed";
        } | {
            /** Format: int64 */
            silence_minutes: number;
            /** @enum {string} */
            type: "no_events";
        } | {
            task_name?: string;
            /** @enum {string} */
            type: "throughput_anomaly";
            /** Format: int64 */
            window_minutes: number;
            /** Format: double */
            zscore_threshold: number;
        } | {
            task_name?: string;
            /** @enum {string} */
            type: "latency_anomaly";
            /** Format: int64 */
            window_minutes: number;
            /** Format: double */
            zscore_threshold: number;
        } | {
            /** Format: int64 */
            baseline_hours: number;
            /** Format: double */
            spike_factor: number;
            task_name: string;
            /** @enum {string} */
            type: "error_rate_spike";
        };
        AlertHistoryParams: {
            /** Format: int64 */
            limit?: number | null;
            /** Format: int64 */
            offset?: number | null;
        };
        AlertHistoryResponse: {
            data: components["schemas"]["AlertHistoryRow"][];
            has_more: boolean;
            /** Format: int64 */
            total?: number | null;
        };
        AlertHistoryRow: {
            channels_sent: {
                [key: string]: components["schemas"]["ChannelDeliveryStatus"];
            };
            details: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            fired_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: uuid */
            rule_id: string;
            severity: string;
            summary: string;
            /** Format: uuid */
            tenant_id: string;
        };
        AlertRule: {
            channels: components["schemas"]["AlertChannel"][];
            condition: components["schemas"]["AlertCondition"];
            /** Format: int32 */
            cooldown_secs: number;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            /** Format: uuid */
            id: string;
            is_enabled: boolean;
            /** Format: date-time */
            last_fired_at?: string | null;
            name: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description List of alert rules. */
        AlertRulesResponse: {
            data: components["schemas"]["AlertRule"][];
        };
        ApiKey: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            key_prefix: string;
            /** Format: date-time */
            last_used_at?: string | null;
            name: string;
            permissions: string[];
            /** Format: uuid */
            tenant_id: string;
        };
        /** @description List of API keys. */
        ApiKeyListResponse: {
            data: components["schemas"]["ApiKey"][];
        };
        /** @description Successful auth response. Tokens are set as HttpOnly cookies, NOT in the body. */
        AuthResponse: {
            /** Format: int64 */
            expires_in: number;
            user: components["schemas"]["UserInfo"];
        };
        BrokerConfig: {
            broker_type: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            last_error?: string | null;
            name: string;
            status: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description List of broker configurations. */
        BrokerListResponse: {
            data: components["schemas"]["BrokerConfig"][];
        };
        /** @description Broker-specific stats for the detail page. */
        BrokerStats: {
            /** Format: int64 */
            events_last_24h: number;
            /** Format: int64 */
            events_last_hour: number;
            /** Format: int64 */
            failure_count: number;
            /** Format: int64 */
            success_count: number;
            top_tasks: components["schemas"]["TopTaskRow"][];
            /** Format: int64 */
            total_events: number;
        };
        /** @description Delivery status for a single notification channel. */
        ChannelDeliveryStatus: {
            error?: string | null;
            success: boolean;
        };
        /** @description Response for task retry/revoke and worker shutdown commands. */
        CommandResponse: {
            command_id?: string | null;
            message?: string | null;
            status: string;
            task_id?: string | null;
        };
        ComponentHealth: {
            /** Format: int64 */
            latency_ms?: number | null;
            message?: string | null;
            name: string;
            status: string;
        };
        CreateAlertRuleRequest: {
            channels: components["schemas"]["AlertChannel"][];
            condition: components["schemas"]["AlertCondition"];
            /** Format: int32 */
            cooldown_secs?: number | null;
            description?: string | null;
            name: string;
        };
        /** @description Response after creating an API key (includes the raw key, shown once). */
        CreateApiKeyResponse: {
            /** Format: uuid */
            id: string;
            key: string;
            key_prefix: string;
            message: string;
            name: string;
        };
        CreateBrokerRequest: {
            broker_type: string;
            connection_url: string;
            name: string;
        };
        CreateKeyRequest: {
            /** Format: date-time */
            expires_at?: string | null;
            name: string;
            permissions: string[];
        };
        /** @description An edge in the workflow DAG. */
        DagEdge: {
            edge_type: components["schemas"]["EdgeType"];
            source: string;
            target: string;
        };
        /** @description A node in the task workflow DAG. */
        DagNode: {
            chord_id?: string | null;
            group_id?: string | null;
            parent_id?: string | null;
            queue: string;
            /** Format: double */
            runtime?: number | null;
            state: string;
            task_id: string;
            task_name: string;
            worker_id: string;
        };
        DeadLetterListResponse: {
            data: components["schemas"]["DeadLetterRow"][];
        };
        DeadLetterRow: {
            /** Format: uuid */
            agent_id: string;
            error_code: string;
            error_message: string;
            /** Format: int32 */
            event_count: number;
            event_type: string;
            /** Format: int64 */
            failed_at: number;
            /** Format: uuid */
            id: string;
            retryable: boolean;
            sample_payload: string;
            /** Format: uuid */
            tenant_id: string;
        };
        DeadLetterSummary: {
            /** Format: int64 */
            last_24h: number;
            /** Format: int64 */
            total: number;
        };
        /** @enum {string} */
        EdgeType: "chain" | "group" | "chord" | "callback";
        FailureGroupRow: {
            /** Format: int64 */
            count: number;
            exception: string;
            /** Format: int64 */
            first_seen: number;
            /** Format: int64 */
            last_seen: number;
            latest_task_id: string;
            latest_traceback: string;
            task_names: string[];
        };
        FailureGroupsParams: {
            /** Format: int64 */
            from_minutes?: number | null;
            /** Format: int64 */
            limit?: number | null;
        };
        FailureGroupsResponse: {
            data: components["schemas"]["FailureGroupRow"][];
        };
        HealthResponse: {
            status: string;
            version: string;
        };
        InviteMemberRequest: {
            email: string;
            role: string;
        };
        /**
         * @description Invite member response.
         *
         *     `invite_url` is always returned so the admin can share the link manually
         *     if email delivery is unavailable or disabled. `email_sent` tells the UI
         *     whether the invite email was also delivered automatically.
         */
        InviteMemberResponse: {
            email: string;
            email_error?: string | null;
            email_sent: boolean;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            invite_id: string;
            invite_url: string;
            role: string;
        };
        InvitePreviewResponse: {
            email: string;
            role: string;
            tenant_name: string;
            tenant_slug: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            /** @description Optional: if the user belongs to multiple orgs, they must specify which one. */
            tenant_slug?: string | null;
        };
        MetricsParams: {
            /**
             * Format: uuid
             * @description Filter by broker/agent ID (for per-broker throughput charts).
             */
            agent_id?: string | null;
            /** Format: int64 */
            from_minutes?: number | null;
            queue?: string | null;
        };
        /** @description Notification settings (SMTP + webhook defaults). */
        NotificationSettings: {
            smtp?: components["schemas"]["SmtpSettings"];
            webhook_defaults?: components["schemas"]["WebhookDefaults"];
        };
        /** @description Returned when the user's email is in multiple orgs and no slug was provided. */
        OrgPickerResponse: {
            needs_org_selection: boolean;
            organizations: components["schemas"]["OrgSummary"][];
        };
        OrgSummary: {
            name: string;
            slug: string;
        };
        /** @description Dashboard overview metrics (computed from ClickHouse + Redis). */
        OverviewResponse: {
            active_workers: number;
            /** Format: double */
            avg_runtime: number;
            /** Format: double */
            avg_wait_time: number;
            /** Format: int64 */
            failure_count: number;
            /** Format: double */
            failure_rate: number;
            /** Format: double */
            p95_runtime: number;
            /** Format: int64 */
            period_minutes: number;
            /** Format: int64 */
            success_count: number;
            /** Format: int64 */
            total_tasks: number;
        };
        /** @description Summary stats for the dashboard overview. */
        OverviewStats: {
            /** Format: double */
            avg_runtime: number;
            /** Format: double */
            avg_wait_time?: number | null;
            /** Format: int64 */
            failure_count: number;
            /** Format: double */
            p95_runtime: number;
            /** Format: int64 */
            success_count: number;
            /** Format: int64 */
            total_tasks: number;
        };
        PipelineStatsResponse: {
            /** Format: double */
            drop_rate: number;
            /** Format: int64 */
            events_dropped: number;
            /** Format: int64 */
            events_inserted: number;
            /** Format: int64 */
            events_parse_failed: number;
            /** Format: int64 */
            events_received: number;
            /** Format: int64 */
            insert_retries: number;
            /** Format: double */
            success_rate: number;
        };
        /** @description Queue depth information. */
        QueueInfo: {
            /** Format: int64 */
            depth: number;
            queue_name: string;
        };
        /** @description List of queue depths from a broker. */
        QueueListResponse: {
            data: components["schemas"]["QueueInfo"][];
        };
        /** @description Queue metrics time-series data. */
        QueueMetricsResponse: {
            data: components["schemas"]["QueueMetricsRow"][];
        };
        /** @description Per-minute queue metrics from the materialized view. */
        QueueMetricsRow: {
            /** Format: int64 */
            completed: number;
            /** Format: int64 */
            dequeued: number;
            /** Format: int64 */
            enqueued: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            minute: number;
            queue: string;
            /** Format: uuid */
            tenant_id: string;
        };
        QueueOverviewResponse: {
            data: components["schemas"]["QueueOverviewRow"][];
        };
        QueueOverviewRow: {
            /** Format: double */
            avg_runtime: number;
            /** Format: int64 */
            backlog: number;
            /** Format: int64 */
            completed: number;
            /** Format: int64 */
            enqueued: number;
            /** Format: int64 */
            failed: number;
            queue: string;
        };
        RegisterRequest: {
            display_name?: string | null;
            email: string;
            password: string;
            tenant_name: string;
            tenant_slug: string;
        };
        RetentionInput: {
            /** Format: int32 */
            alert_history_days: number;
            /** Format: int32 */
            task_events_days: number;
            /** Format: int32 */
            worker_events_days: number;
        };
        RetentionPolicy: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            resource_type: string;
            /** Format: int32 */
            retention_days: number;
            /** Format: uuid */
            tenant_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Data retention configuration. */
        RetentionResponse: {
            /** Format: int32 */
            alert_history_days: number;
            /** Format: int32 */
            task_events_days: number;
            /** Format: int32 */
            worker_events_days: number;
        };
        /** @description A single attempt in a retry chain. */
        RetryAttempt: {
            exception: string;
            /** Format: int32 */
            retries: number;
            /** Format: double */
            runtime: number;
            state: string;
            task_id: string;
            /** Format: int64 */
            timestamp_ms: number;
            worker_id: string;
        };
        /** @description Full retry chain for a task. */
        RetryChainResponse: {
            attempts: components["schemas"]["RetryAttempt"][];
            origin_task_id: string;
            task_name: string;
        };
        RetryRequest: {
            args: unknown;
            kwargs: unknown;
            queue: string;
            task_name: string;
        };
        Role: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            is_system: boolean;
            name: string;
            permissions: string[];
            /** Format: uuid */
            tenant_id: string;
        };
        SetupStatusResponse: {
            allow_signup: boolean;
            needs_setup: boolean;
        };
        SmtpSettings: {
            from_address?: string;
            host?: string;
            /** Format: int32 */
            port?: number;
            tls?: boolean;
            username?: string;
        };
        StorageInfo: {
            /** Format: int64 */
            free_bytes: number;
            tables: components["schemas"]["TableStorageRow"][];
            /** Format: int64 */
            total_bytes: number;
            /** Format: int64 */
            used_bytes: number;
        };
        /** @description List of string values (task names, queue names). */
        StringListResponse: {
            data: string[];
        };
        /** @description Switch to a different org (re-issues tokens for that org). */
        SwitchOrgRequest: {
            tenant_slug: string;
        };
        SystemHealthResponse: {
            components: components["schemas"]["ComponentHealth"][];
            dead_letters?: null | components["schemas"]["DeadLetterSummary"];
            pipeline: components["schemas"]["PipelineStatsResponse"];
            status: string;
            storage?: null | components["schemas"]["StorageInfo"];
            version: string;
        };
        TableStorageRow: {
            /** Format: int64 */
            bytes_on_disk: number;
            /** Format: int64 */
            rows: number;
            table: string;
        };
        /** @description ClickHouse row type for task_events table. */
        TaskEventRow: {
            /** Format: uuid */
            agent_id: string;
            args: string;
            broker_type: string;
            chord_id?: string | null;
            /** Format: uuid */
            event_id: string;
            event_type: string;
            exception: string;
            group_id?: string | null;
            kwargs: string;
            parent_id?: string | null;
            queue: string;
            result: string;
            /** Format: int32 */
            retries: number;
            root_id?: string | null;
            /** Format: double */
            runtime: number;
            state: string;
            task_id: string;
            task_name: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: int64 */
            timestamp: number;
            traceback: string;
            worker_id: string;
        };
        TaskListParams: {
            cursor?: string | null;
            /**
             * @description Present-and-true restricts results to tasks with a non-empty exception.
             *     `false` is treated as "no filter" for URL friendliness — use `errors_only=true` or omit.
             */
            errors_only?: boolean | null;
            /** Format: int64 */
            limit?: number | null;
            queue?: string | null;
            /**
             * @description Free-text substring search across task_id, task_name, args, kwargs,
             *     result, and exception.
             */
            search?: string | null;
            /**
             * Format: int64
             * @description Lower bound on `timestamp` (millis since epoch, inclusive).
             */
            since_ms?: number | null;
            state?: string | null;
            task_name?: string | null;
            /**
             * Format: int64
             * @description Upper bound on `timestamp` (millis since epoch, inclusive).
             */
            until_ms?: number | null;
            worker_id?: string | null;
        };
        TaskListResponse: {
            data: components["schemas"]["TaskEventRow"][];
            has_more: boolean;
            next_cursor?: string | null;
            /** Format: int64 */
            total?: number | null;
        };
        /** @description Per-minute task metrics from the materialized view. */
        TaskMetricsRow: {
            /** Format: int64 */
            failure_count: number;
            /** Format: double */
            max_runtime: number;
            /** Format: int64 */
            minute: number;
            queue: string;
            /** Format: int64 */
            retry_count: number;
            /** Format: int64 */
            revoked_count: number;
            /** Format: int64 */
            success_count: number;
            task_name: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: int64 */
            total_count: number;
            /** Format: double */
            total_runtime: number;
            /** Format: double */
            total_wait_time?: number | null;
            /** Format: int64 */
            wait_time_samples: number;
        };
        TaskNameStatsResponse: {
            data: components["schemas"]["TaskNameStatsRow"][];
        };
        TaskNameStatsRow: {
            /** Format: double */
            avg_runtime: number;
            /** Format: double */
            avg_wait: number;
            /** Format: int64 */
            failure: number;
            /** Format: double */
            max_runtime: number;
            /** Format: double */
            p95_runtime: number;
            /** Format: double */
            p99_runtime: number;
            /** Format: int64 */
            retry: number;
            /** Format: int64 */
            success: number;
            task_name: string;
            /** Format: int64 */
            total: number;
        };
        TaskSummaryListResponse: {
            data: components["schemas"]["TaskSummaryRow"][];
            has_more: boolean;
            next_cursor?: string | null;
        };
        TaskSummaryRow: {
            exception: string;
            queue: string;
            /** Format: int32 */
            retries: number;
            /** Format: double */
            runtime: number;
            state: string;
            task_id: string;
            task_name: string;
            /** Format: int64 */
            timestamp: number;
            /** Format: double */
            wait_seconds: number;
            worker_id: string;
        };
        /** @description Task event timeline (all state transitions for a single task). */
        TaskTimelineResponse: {
            timeline: components["schemas"]["TaskEventRow"][];
        };
        /** @description Team member (user with roles). */
        TeamMember: {
            /** Format: date-time */
            created_at: string;
            display_name?: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            roles: string[];
        };
        /** @description Team response (members + available roles). */
        TeamResponse: {
            members: components["schemas"]["TeamMember"][];
            roles: components["schemas"]["Role"][];
        };
        Tenant: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            /** Format: int32 */
            max_agents: number;
            /** Format: int64 */
            max_events_day: number;
            name: string;
            plan: string;
            settings: unknown;
            slug: string;
            /** Format: date-time */
            updated_at: string;
        };
        TestConnectionRequest: {
            broker_type: string;
            connection_url: string;
        };
        /** @description Broker connection test result. */
        TestConnectionResponse: {
            error?: string | null;
            success: boolean;
        };
        TestNotificationRequest: {
            channel: string;
            to?: string | null;
        };
        /** @description Throughput time-series data. */
        ThroughputResponse: {
            data: components["schemas"]["TaskMetricsRow"][];
        };
        TopTaskRow: {
            /** Format: int64 */
            count: number;
            name: string;
        };
        UpdateAlertRuleRequest: {
            channels: components["schemas"]["AlertChannel"][];
            condition: components["schemas"]["AlertCondition"];
            /** Format: int32 */
            cooldown_secs: number;
            description?: string | null;
            is_enabled: boolean;
            name: string;
        };
        UserInfo: {
            display_name?: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            /**
             * @description Permission strings (e.g. "alerts_write"). Empty for admins — they're
             *     allowed everything by virtue of the "admin" role.
             */
            permissions: string[];
            roles: string[];
            /** Format: uuid */
            tenant_id: string;
            tenant_slug: string;
        };
        WebhookDefaults: {
            /** Format: int32 */
            retry_count?: number;
            /** Format: int32 */
            timeout_seconds?: number;
        };
        /** @description Single worker detail with current state and recent events. */
        WorkerDetailResponse: {
            current_state?: null | components["schemas"]["WorkerState"];
            recent_events: components["schemas"]["WorkerEventRow"][];
            worker_id: string;
        };
        WorkerEventRow: {
            /** Format: int32 */
            active_tasks: number;
            /** Format: uuid */
            agent_id: string;
            /** Format: double */
            cpu_percent: number;
            /** Format: uuid */
            event_id: string;
            event_type: string;
            hostname: string;
            load_avg: number[];
            /** Format: double */
            memory_mb: number;
            /** Format: int32 */
            pool_size: number;
            pool_type: string;
            /** Format: int64 */
            processed: number;
            sw_ident: string;
            sw_ver: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: int64 */
            timestamp: number;
            worker_id: string;
        };
        WorkerHealthParams: {
            /**
             * Format: int64
             * @description Lookback period in hours (default: 1)
             */
            hours?: number | null;
        };
        /** @description Per-worker heartbeat health with real-time TTL and historical gap analysis. */
        WorkerHealthResponse: {
            data: components["schemas"]["WorkerHealthRow"][];
        };
        WorkerHealthRow: {
            /** Format: int32 */
            active_tasks: number;
            /** Format: double */
            avg_gap_secs: number;
            /** Format: int64 */
            heartbeat_count: number;
            /** Format: int64 */
            heartbeat_ttl: number;
            /** Format: int64 */
            last_heartbeat?: number | null;
            /** Format: double */
            load_avg: number;
            /** Format: double */
            max_gap_secs: number;
            status: string;
            worker_id: string;
        };
        /** @description Per-worker heartbeat health metrics (last N hours from sampled heartbeats). */
        WorkerHeartbeatHealthRow: {
            /** Format: int32 */
            active_tasks: number;
            /** Format: double */
            avg_gap_secs: number;
            /** Format: int64 */
            heartbeat_count: number;
            /** Format: int64 */
            last_heartbeat: number;
            /** Format: double */
            load_avg: number;
            /** Format: double */
            max_gap_secs: number;
            worker_id: string;
        };
        WorkerListParams: {
            /** Format: int64 */
            limit?: number | null;
            status?: string | null;
        };
        /** @description Worker list with online set, ClickHouse events, and Redis states. */
        WorkerListResponse: {
            online_workers: string[];
            worker_events: components["schemas"]["WorkerEventRow"][];
            worker_states: components["schemas"]["WorkerState"][];
        };
        /** @description Cached worker state from Redis (set by broker pipeline on heartbeat events). */
        WorkerState: {
            /** Format: int32 */
            active_tasks: number;
            /** Format: double */
            cpu_percent: number;
            hostname: string;
            load_avg: number[];
            /** Format: double */
            memory_mb: number;
            /** Format: int32 */
            pool_size: number;
            pool_type: string;
            /** Format: int64 */
            processed: number;
            status: string;
            sw_ident: string;
            sw_ver: string;
            worker_id: string;
        };
        /** @description Per-worker task stats (pending, running, done, failed) from last 24h. */
        WorkerTaskStatsResponse: {
            data: components["schemas"]["WorkerTaskStatsRow"][];
        };
        /** @description Per-worker task stats aggregated from task_events (last 24 hours). */
        WorkerTaskStatsRow: {
            /** Format: double */
            avg_runtime: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            pending: number;
            /** Format: int64 */
            retried: number;
            /** Format: int64 */
            revoked: number;
            /** Format: int64 */
            started: number;
            /** Format: int64 */
            succeeded: number;
            /** Format: int64 */
            total: number;
            worker_id: string;
        };
        /** @description Complete workflow DAG. */
        WorkflowDag: {
            edges: components["schemas"]["DagEdge"][];
            nodes: components["schemas"]["DagNode"][];
            root_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_history: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertHistoryResponse"];
                };
            };
        };
    };
    list_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRulesResponse"];
                };
            };
        };
    };
    create_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    get_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Alert rule ID */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    update_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Alert rule ID */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    delete_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Alert rule ID */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyListResponse"];
                };
            };
        };
    };
    create_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApiKeyResponse"];
                };
            };
        };
    };
    revoke_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    accept_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite not found or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite token */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewResponse"];
                };
            };
            /** @description Invite not found or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Org selection needed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgPickerResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_user_orgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSummary"][];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    switch_org: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrgRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Not a member */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_brokers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerListResponse"];
                };
            };
        };
    };
    create_broker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrokerRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerConfig"];
                };
            };
        };
    };
    test_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
        };
    };
    get_broker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerConfig"];
                };
            };
        };
    };
    delete_broker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_broker_queues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueListResponse"];
                };
            };
        };
    };
    start_broker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_broker_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerStats"];
                };
            };
        };
    };
    stop_broker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broker ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    failure_groups: {
        parameters: {
            query?: {
                from_minutes?: number | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureGroupsResponse"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: {
                from_minutes?: number | null;
                queue?: string | null;
                /** @description Filter by broker/agent ID (for per-broker throughput charts). */
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    queue_names: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StringListResponse"];
                };
            };
        };
    };
    queue_overview: {
        parameters: {
            query?: {
                from_minutes?: number | null;
                queue?: string | null;
                /** @description Filter by broker/agent ID (for per-broker throughput charts). */
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueOverviewResponse"];
                };
            };
        };
    };
    queue_metrics: {
        parameters: {
            query?: {
                from_minutes?: number | null;
                queue?: string | null;
                /** @description Filter by broker/agent ID (for per-broker throughput charts). */
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueMetricsResponse"];
                };
            };
        };
    };
    task_name_stats: {
        parameters: {
            query?: {
                from_minutes?: number | null;
                queue?: string | null;
                /** @description Filter by broker/agent ID (for per-broker throughput charts). */
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskNameStatsResponse"];
                };
            };
        };
    };
    task_names: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StringListResponse"];
                };
            };
        };
    };
    throughput: {
        parameters: {
            query?: {
                from_minutes?: number | null;
                queue?: string | null;
                /** @description Filter by broker/agent ID (for per-broker throughput charts). */
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputResponse"];
                };
            };
        };
    };
    list_queues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StringListResponse"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
        };
    };
    get_notifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
        };
    };
    update_notifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettings"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
        };
    };
    test_notification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestNotificationRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_retention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionResponse"];
                };
            };
        };
    };
    update_retention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetentionInput"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionResponse"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    dead_letters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dead letter entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadLetterListResponse"];
                };
            };
        };
    };
    system_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealthResponse"];
                };
            };
        };
    };
    pipeline_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatsResponse"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: {
                state?: string | null;
                task_name?: string | null;
                queue?: string | null;
                worker_id?: string | null;
                /**
                 * @description Free-text substring search across task_id, task_name, args, kwargs,
                 *     result, and exception.
                 */
                search?: string | null;
                /**
                 * @description Present-and-true restricts results to tasks with a non-empty exception.
                 *     `false` is treated as "no filter" for URL friendliness — use `errors_only=true` or omit.
                 */
                errors_only?: boolean | null;
                /** @description Lower bound on `timestamp` (millis since epoch, inclusive). */
                since_ms?: number | null;
                /** @description Upper bound on `timestamp` (millis since epoch, inclusive). */
                until_ms?: number | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    list_task_summary: {
        parameters: {
            query?: {
                state?: string | null;
                task_name?: string | null;
                queue?: string | null;
                worker_id?: string | null;
                /**
                 * @description Free-text substring search across task_id, task_name, args, kwargs,
                 *     result, and exception.
                 */
                search?: string | null;
                /**
                 * @description Present-and-true restricts results to tasks with a non-empty exception.
                 *     `false` is treated as "no filter" for URL friendliness — use `errors_only=true` or omit.
                 */
                errors_only?: boolean | null;
                /** @description Lower bound on `timestamp` (millis since epoch, inclusive). */
                since_ms?: number | null;
                /** @description Upper bound on `timestamp` (millis since epoch, inclusive). */
                until_ms?: number | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task-centric summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummaryListResponse"];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEventRow"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
        };
    };
    get_retry_chain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Any task ID in the retry chain */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryChainResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
        };
    };
    get_task_timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTimelineResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_team: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
        };
    };
    invite_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteMemberResponse"];
                };
            };
        };
    };
    remove_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member ID */
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_workers: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerListResponse"];
                };
            };
        };
    };
    worker_health: {
        parameters: {
            query?: {
                /** @description Lookback period in hours (default: 1) */
                hours?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-worker heartbeat health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerHealthResponse"];
                };
            };
        };
    };
    worker_task_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-worker task stats (24h) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerTaskStatsResponse"];
                };
            };
        };
    };
    get_worker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Worker ID */
                worker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerDetailResponse"];
                };
            };
        };
    };
    shutdown_worker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Worker ID */
                worker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
        };
    };
    get_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Root task ID */
                root_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow DAG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDag"];
                };
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
