apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: feloxi-postgres
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feloxi-postgres
  serviceName: feloxi-postgres
  template:
    metadata:
      labels:
        app: feloxi-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-bookworm
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: feloxi-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: feloxi-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: feloxi-secrets
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "fp", "-d", "feloxi"]
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "fp", "-d", "feloxi"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: feloxi-postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: feloxi-postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: feloxi-postgres
  namespace: core
spec:
  selector:
    app: feloxi-postgres
  ports:
    - port: 5432
      targetPort: 5432
