apiVersion: v1
kind: Service
metadata:
  name: {{ include "feloxi.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feloxi.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "feloxi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
